# Site settings
title: Rafal's research reading blog
email: Rafal.Kocielnik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my research blog during a PhD at Human Centered Design & Engineering 
  department at University of Washington in Seattle, US.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.rkocielnik.com" # the base hostname & protocol for your site
github_username:  kaminari84

# Build settings
markdown: kramdown
